import os
import time

# --- ACTION IMPLEMENTATIONS ---
from sentence_transformers import SentenceTransformer
from app.utils.faiss_store import FaissStore

def rag_query(params: dict):
    query = params.get("query", "")
    model = SentenceTransformer("all-MiniLM-L6-v2")
    store = FaissStore(dim=384)

    query_embedding = model.encode([query])
    results = store.search(query_embedding)

    return {
        "context": results,
        "count": len(results)
    }

def retrieve_documents(params: dict):
    """
    Simulate document retrieval.
    Later this will connect to RAG ingestion.
    """
    time.sleep(1)
    docs = ["doc1.txt", "doc2.txt"]
    return {
        "documents": docs,
        "count": len(docs)
    }

def generate_report(params: dict):
    context = params.get("context", [])

    filename = "report.txt"
    with open(filename, "w") as f:
        f.write("AUTOGENERATED REPORT\n\n")
        for c in context:
            f.write(f"- {c}\n")

    return {
        "file": filename,
        "lines": len(context)
    }


def send_email(params: dict):
    """
    Dry-run email sender.
    """
    time.sleep(1)
    return {
        "status": "sent",
        "mode": params.get("mode", "dry_run")
    }

def clarify_intent(params: dict):
    return {
        "question": params.get("question")
    }

# --- ACTION REGISTRY ---

ACTION_REGISTRY = {
    "retrieve_documents": retrieve_documents,
    "generate_report": generate_report,
    "send_email": send_email,
    "clarify_intent": clarify_intent,
    "rag_query": rag_query
}
